### ISSUE TITLE
False positive: exception on immutable functions

### ISSUE THREAD

**Issue by rts-barry** [okbob/plpgsql_check#18]
This is a very obscure one. It occurs when a function calls an __immutable__ function which raises an exception on the first branch (when buried inside an if-statement it doesn't trigger).
I think it happens because immutable functions get in-lined.

```sql
create or replace function a() RETURNS VOID AS $$
BEGIN
   IF FALSE THEN
      PERFORM b('a');
   END IF;
END;
$$ LANGUAGE PLPGSQL;


create or replace function b(TEXT) RETURNS VOID AS $$
BEGIN
   RAISE EXCEPTION USING MESSAGE = format('function %s (called fail)', $1) ;
END;
$$ LANGUAGE PLPGSQL IMMUTABLE;

load 'plpgsql';
select plpgsql_check_function('a()');
-- "error:P0001:4:PERFORM:function a (called fail)"
```

Changing function b() here to VOLATILE removes the false positive.

**Comment by okbob** [comment]
2015-08-24 10:52 GMT+02:00 rts-barry <notifications@github.com>:

> This is a very obscure one. It occurs when a function calls an *immutable*
> function which raises an exception on the first branch (when buried inside
> an if-statement it doesn't trigger).
> I think it happens because immutable functions get in-lined.
>
it is strange - plpgsql functions are not inlined

**Comment by okbob** [comment]
I understand to this bug now - and this bug is really related to IMMUTABLE flag. plpgsql_check uses SQL parser and (against to plpgsql builtin validator) SQL planner. One optimization there is early function evaluation - all immutable functions with constant parameters are evaluated in planning time and function's call is replaced by constant. PERFORM b('a') is transformed to SELECT b('a'), and due IMMUTABLE of b and constant parameter, the function is started - and failed on your custom exception. 

I am thinking so this is not plpgsql_bug. Any function with any side effect should be marked as VOLATILE. Theoretically I can hide P0001 and similar exceptions, but I am not sure, it it is well. Current behave can show these issues.

**Comment by rts-barry** [comment]
Thanks for figuring this out. I was myself doubting whether or not this was a bug in plpgsql_check.
The correct flag for the function should really be VOLATILE in this case.
