### ISSUE TITLE
Test file: expected/plpgsql_check_passive_2.out file not matching pg9.4 output

### ISSUE THREAD

**Issue by shuehner** [okbob/plpgsql_check#55]
Hello,
while working on Debian / Ubuntu packaging for your extensions the maintainer ran the regression tests against all active PostgreSQL versions and noticed a problem with the plpgsql_check_passive_2.out file.

Problem is that pg9.4 is showing less context on errors causing it to not match the expected output given in the _2.out file.

Probably a pg9.4 specific out file is required here to have the test pass cleanly.

Difference can be seen here:
https://pgdgbuild.dus.dg-i.net/job/plpgsql-check-binaries/1/architecture=amd64,distribution=sid/consoleFull
when searching for "plpgsql_check_passive_2.out"

Note:
pg9.4 is getting close to its end of live having only 2 month left.
https://www.postgresql.org/support/versioning/

**Comment by okbob** [comment]
po 9. 12. 2019 v 17:34 odesílatel Stefan Hühner <notifications@github.com>
napsal:

> Hello,
> while working on Debian / Ubuntu packaging for your extensions the
> maintainer ran the regression tests against all active PostgreSQL versions
> and noticed a problem with the plpgsql_check_passive_2.out file.
>
> Problem is that pg9.4 is showing less context on errors causing it to not
> match the expected output given in the _2.out file.
>
> Probably a pg9.4 specific out file is required here to have the test pass
> cleanly.
>
> Difference can be seen here:
>
> https://pgdgbuild.dus.dg-i.net/job/plpgsql-check-binaries/1/architecture=amd64,distribution=sid/consoleFull
> when searching for "plpgsql_check_passive_2.out"
>
> Note:
> pg9.4 is getting close to its end of live having only 2 month left.
> https://www.postgresql.org/support/versioning/
>

It doesn't looks well - I checked it locally and it is works. It looks so
debian on 9.4 has disabled CONTEXT info. Maybe there is some debian
customization there. It doesn't look like default psql behave. I cannot to
fix it simply, because then I will break this test for RH :/

Probably there is one solution - create new plpgsql_check_passive_3.out
with your result without context lines. Please, can me send pull request
with this file?

**Comment by okbob** [comment]
I removed support for 9.4.
